name: Check Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 24

jobs:
  check:
    runs-on: amd64
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Testing
        run: pnpm run test

      - name: Log into repository
        uses: docker/login-action@v3
        with:
          registry: git.postfmly.com
          username: admin
          password: ${{ secrets.PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: |
          docker buildx build \
            --tag git.postfmly.com/admin/sober:latest \
            --platform linux/amd64,linux/arm64
            --push .
