name: Build Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          cache: true
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Testing
        run: pnpm run test

      - name: Build image
        run: docker build --tag=git.postfmly.com/admin/sober .

      - name: Log in
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.PASSWORD }}
          registry: git.postfmly.com
          username: admin

      - name: Push image
        run: docker image push git.postfmly.com/admin/sober
