name: Check Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Testing
        run: pnpm run test
