name: Build Sᴏʙᴇᴙ Tᴙᴀᴄᴋᴇᴙ

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Testing
        run: pnpm run test

      - name: Log in
        uses: docker/login-action@v3
        with:
          registry: git.postfmly.com
          username: admin
          password: ${{ secrets.PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: admin/sober
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PASSWORD }}
